name: 'Readability helper'
description: 'Analyzes your text and returns readability scores'
inputs:
  auth-token:
    description: Authentication token with access to repository
    required: true
  files-in-scope:
    description: Array of files in scope to be analyzed (relative path)
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'